name = "modpack"
author = "HexoKnight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe3b118a488295e9f9bca158d985309a06b01f30bc2b348e051c5bc591afc7b"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
