#!/usr/bin/env bash

PATH=@playerctl@/bin:$PATH

playerctl --player=playerctld,%any --follow metadata --format '{{ status }} {{ artist }} - {{ title }} [{{ duration(position) }}/{{ duration(mpris:length) }}]' |
    sed --unbuffered '
        # replace status with emoji
        s/^Playing// # 󰐊
        s/^Paused// # 󰏤
        s/^Stopped// # 󰓛

        # remove extraneous dash if artist is unavailable
        s/^\(\S\+\)  -/\1/
    '
